---
- name: Set up XO Container
  hosts: lxc
  gather_facts: true
  user: "{{ user }}"
  become: true
  become_method: sudo

  roles:
    - lxc

- name: Set Up XO
  hosts: xo
  gather_facts: true
  user: "{{ user }}"
  become: true
  become_method: sudo

  roles:
    - xo
